version: '2.2'

services:
  mongo:
    image: mongo
    volumes:
      - /data/db
    ports:
      - 27017:27017


  mongo-express:
    image: mongo-express
    ports:
      - 3333:8081
    scale: 0
    depends_on:
      - mongo

  rails:
    build: ./rails
    ports:
      - 3000:3000
    depends_on:
      - flask
    volumes:
      - ./rails:/code
      - ./data/images2440:/code/public/brandimages
    command: bash -c "bundle install && rails server -b 0.0.0.0"

  flask:
    build: ./flask
    # working_dir: /code
    ports:
      - 5000:5000
    volumes:
      - ./flask:/code
      - ./model_data:/model_data
      - ./models:/models
      - ./data:/data
    environment:
      SPARK_CONF_DIR: /code/spark-conf
      MASTER: spark://master:7077
      PYTHONHASHSEED: 64
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    command: python main.py
    depends_on:
      - master
      - worker
      - mongo


  master:
    build: ./spark
    image: cgarciae/pyspark-notebook:2.1.1
    working_dir: /usr/local/spark
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
      - 8020
    volumes:
      - ./spark-master:/conf
    depends_on:
      - hadoop


  worker:
    build: ./spark
    image: cgarciae/pyspark-notebook:2.1.1
    working_dir: /usr/local/spark
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    hostname: worker
    user: root
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    volumes:
      - ./spark-worker:/conf
    scale: 2
    depends_on:
      - master

  hadoop:
    image: sequenceiq/hadoop-docker
    ports:
      - 50070:50070
    expose:
      - 9000
    hostname: hadoop
