
version: '2'

volumes:
  nvidia_driver_375.66:
    external: true


services:
  test:
    image: nvidia/cuda
    volumes:
      - nvidia_driver_375.66:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    command: nvidia-smi
