# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e13417d9fb7f5bff5448c2df820f02be9f8ba876491567bdf4b641aa42951ffcd81fd969bcdf9250da48baef098f962c1293e5395ff168e86a72b5b61f7a3b7e

test:
  secret_key_base: 360fb1a0f8c25f4147261364d928ddd432755a13ed872838abcfc2837e7816820a29cc0816f0a0b3edaf360dc71c2278f229bcb30b801ad9487d8a2d5ac25ae6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
